<?php
/**
 * DefaultApi
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\goexpress
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GO! Connect Realtime Order & Label API
 *
 * API for creating, updating, canceling shipments and generating labels for GO! Express & Logistics.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\goexpress\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use kruegge82\goexpress\ApiException;
use kruegge82\goexpress\Configuration;
use kruegge82\goexpress\FormDataProcessor;
use kruegge82\goexpress\HeaderSelector;
use kruegge82\goexpress\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\goexpress
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'labelApiV1GenerateLabelForhwbPost' => [
            'application/json',
        ],
        'orderApiV1CreateOrderPost' => [
            'application/json',
        ],
        'orderApiV1UpdateOrderStatusPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation labelApiV1GenerateLabelForhwbPost
     *
     * Generate label for existing HWB
     *
     * @param  \kruegge82\goexpress\Model\LabelRequest $label_request label_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelApiV1GenerateLabelForhwbPost'] to see the possible values for this operation
     *
     * @throws \kruegge82\goexpress\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function labelApiV1GenerateLabelForhwbPost($label_request, string $contentType = self::contentTypes['labelApiV1GenerateLabelForhwbPost'][0])
    {
        $this->labelApiV1GenerateLabelForhwbPostWithHttpInfo($label_request, $contentType);
    }

    /**
     * Operation labelApiV1GenerateLabelForhwbPostWithHttpInfo
     *
     * Generate label for existing HWB
     *
     * @param  \kruegge82\goexpress\Model\LabelRequest $label_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelApiV1GenerateLabelForhwbPost'] to see the possible values for this operation
     *
     * @throws \kruegge82\goexpress\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function labelApiV1GenerateLabelForhwbPostWithHttpInfo($label_request, string $contentType = self::contentTypes['labelApiV1GenerateLabelForhwbPost'][0])
    {
        $request = $this->labelApiV1GenerateLabelForhwbPostRequest($label_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation labelApiV1GenerateLabelForhwbPostAsync
     *
     * Generate label for existing HWB
     *
     * @param  \kruegge82\goexpress\Model\LabelRequest $label_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelApiV1GenerateLabelForhwbPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function labelApiV1GenerateLabelForhwbPostAsync($label_request, string $contentType = self::contentTypes['labelApiV1GenerateLabelForhwbPost'][0])
    {
        return $this->labelApiV1GenerateLabelForhwbPostAsyncWithHttpInfo($label_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation labelApiV1GenerateLabelForhwbPostAsyncWithHttpInfo
     *
     * Generate label for existing HWB
     *
     * @param  \kruegge82\goexpress\Model\LabelRequest $label_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelApiV1GenerateLabelForhwbPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function labelApiV1GenerateLabelForhwbPostAsyncWithHttpInfo($label_request, string $contentType = self::contentTypes['labelApiV1GenerateLabelForhwbPost'][0])
    {
        $returnType = '';
        $request = $this->labelApiV1GenerateLabelForhwbPostRequest($label_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'labelApiV1GenerateLabelForhwbPost'
     *
     * @param  \kruegge82\goexpress\Model\LabelRequest $label_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelApiV1GenerateLabelForhwbPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function labelApiV1GenerateLabelForhwbPostRequest($label_request, string $contentType = self::contentTypes['labelApiV1GenerateLabelForhwbPost'][0])
    {

        // verify the required parameter 'label_request' is set
        if ($label_request === null || (is_array($label_request) && count($label_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $label_request when calling labelApiV1GenerateLabelForhwbPost'
            );
        }


        $resourcePath = '/label/api/v1/generateLabelForhwb';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($label_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($label_request));
            } else {
                $httpBody = $label_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderApiV1CreateOrderPost
     *
     * Create or update shipment order
     *
     * @param  \kruegge82\goexpress\Model\OrderRequest $order_request order_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1CreateOrderPost'] to see the possible values for this operation
     *
     * @throws \kruegge82\goexpress\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \kruegge82\goexpress\Model\OrderResponse
     */
    public function orderApiV1CreateOrderPost($order_request, string $contentType = self::contentTypes['orderApiV1CreateOrderPost'][0])
    {
        list($response) = $this->orderApiV1CreateOrderPostWithHttpInfo($order_request, $contentType);
        return $response;
    }

    /**
     * Operation orderApiV1CreateOrderPostWithHttpInfo
     *
     * Create or update shipment order
     *
     * @param  \kruegge82\goexpress\Model\OrderRequest $order_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1CreateOrderPost'] to see the possible values for this operation
     *
     * @throws \kruegge82\goexpress\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \kruegge82\goexpress\Model\OrderResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderApiV1CreateOrderPostWithHttpInfo($order_request, string $contentType = self::contentTypes['orderApiV1CreateOrderPost'][0])
    {
        $request = $this->orderApiV1CreateOrderPostRequest($order_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\kruegge82\goexpress\Model\OrderResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\kruegge82\goexpress\Model\OrderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kruegge82\goexpress\Model\OrderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation orderApiV1CreateOrderPostAsync
     *
     * Create or update shipment order
     *
     * @param  \kruegge82\goexpress\Model\OrderRequest $order_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1CreateOrderPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1CreateOrderPostAsync($order_request, string $contentType = self::contentTypes['orderApiV1CreateOrderPost'][0])
    {
        return $this->orderApiV1CreateOrderPostAsyncWithHttpInfo($order_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderApiV1CreateOrderPostAsyncWithHttpInfo
     *
     * Create or update shipment order
     *
     * @param  \kruegge82\goexpress\Model\OrderRequest $order_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1CreateOrderPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1CreateOrderPostAsyncWithHttpInfo($order_request, string $contentType = self::contentTypes['orderApiV1CreateOrderPost'][0])
    {
        $returnType = '\kruegge82\goexpress\Model\OrderResponse';
        $request = $this->orderApiV1CreateOrderPostRequest($order_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderApiV1CreateOrderPost'
     *
     * @param  \kruegge82\goexpress\Model\OrderRequest $order_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1CreateOrderPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function orderApiV1CreateOrderPostRequest($order_request, string $contentType = self::contentTypes['orderApiV1CreateOrderPost'][0])
    {

        // verify the required parameter 'order_request' is set
        if ($order_request === null || (is_array($order_request) && count($order_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_request when calling orderApiV1CreateOrderPost'
            );
        }


        $resourcePath = '/order/api/v1/createOrder';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($order_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($order_request));
            } else {
                $httpBody = $order_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderApiV1UpdateOrderStatusPost
     *
     * Update order status
     *
     * @param  \kruegge82\goexpress\Model\UpdateStatusRequest $update_status_request update_status_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1UpdateOrderStatusPost'] to see the possible values for this operation
     *
     * @throws \kruegge82\goexpress\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \kruegge82\goexpress\Model\OrderResponse
     */
    public function orderApiV1UpdateOrderStatusPost($update_status_request, string $contentType = self::contentTypes['orderApiV1UpdateOrderStatusPost'][0])
    {
        list($response) = $this->orderApiV1UpdateOrderStatusPostWithHttpInfo($update_status_request, $contentType);
        return $response;
    }

    /**
     * Operation orderApiV1UpdateOrderStatusPostWithHttpInfo
     *
     * Update order status
     *
     * @param  \kruegge82\goexpress\Model\UpdateStatusRequest $update_status_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1UpdateOrderStatusPost'] to see the possible values for this operation
     *
     * @throws \kruegge82\goexpress\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \kruegge82\goexpress\Model\OrderResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderApiV1UpdateOrderStatusPostWithHttpInfo($update_status_request, string $contentType = self::contentTypes['orderApiV1UpdateOrderStatusPost'][0])
    {
        $request = $this->orderApiV1UpdateOrderStatusPostRequest($update_status_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\kruegge82\goexpress\Model\OrderResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\kruegge82\goexpress\Model\OrderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kruegge82\goexpress\Model\OrderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation orderApiV1UpdateOrderStatusPostAsync
     *
     * Update order status
     *
     * @param  \kruegge82\goexpress\Model\UpdateStatusRequest $update_status_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1UpdateOrderStatusPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1UpdateOrderStatusPostAsync($update_status_request, string $contentType = self::contentTypes['orderApiV1UpdateOrderStatusPost'][0])
    {
        return $this->orderApiV1UpdateOrderStatusPostAsyncWithHttpInfo($update_status_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderApiV1UpdateOrderStatusPostAsyncWithHttpInfo
     *
     * Update order status
     *
     * @param  \kruegge82\goexpress\Model\UpdateStatusRequest $update_status_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1UpdateOrderStatusPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1UpdateOrderStatusPostAsyncWithHttpInfo($update_status_request, string $contentType = self::contentTypes['orderApiV1UpdateOrderStatusPost'][0])
    {
        $returnType = '\kruegge82\goexpress\Model\OrderResponse';
        $request = $this->orderApiV1UpdateOrderStatusPostRequest($update_status_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderApiV1UpdateOrderStatusPost'
     *
     * @param  \kruegge82\goexpress\Model\UpdateStatusRequest $update_status_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1UpdateOrderStatusPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function orderApiV1UpdateOrderStatusPostRequest($update_status_request, string $contentType = self::contentTypes['orderApiV1UpdateOrderStatusPost'][0])
    {

        // verify the required parameter 'update_status_request' is set
        if ($update_status_request === null || (is_array($update_status_request) && count($update_status_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_status_request when calling orderApiV1UpdateOrderStatusPost'
            );
        }


        $resourcePath = '/order/api/v1/updateOrderStatus';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_status_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_status_request));
            } else {
                $httpBody = $update_status_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
