<?php
/**
 * TimeWindow
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\goexpress
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GO! Connect Realtime Order & Label API
 *
 * API for creating, updating, canceling shipments and generating labels for GO! Express & Logistics.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\goexpress\Model;

use \ArrayAccess;
use \kruegge82\goexpress\ObjectSerializer;

/**
 * TimeWindow Class Doc Comment
 *
 * @category Class
 * @description Object defining date and time windows for pickup or delivery.
 * @package  kruegge82\goexpress
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimeWindow implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TimeWindow';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'date' => 'string',
        'time_from' => 'string',
        'time_till' => 'string',
        'avis_from' => 'string',
        'avis_till' => 'string',
        'weekend_or_holiday_indicator' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'date' => null,
        'time_from' => null,
        'time_till' => null,
        'avis_from' => null,
        'avis_till' => null,
        'weekend_or_holiday_indicator' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'date' => false,
        'time_from' => false,
        'time_till' => false,
        'avis_from' => false,
        'avis_till' => false,
        'weekend_or_holiday_indicator' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date' => 'date',
        'time_from' => 'timeFrom',
        'time_till' => 'timeTill',
        'avis_from' => 'avisFrom',
        'avis_till' => 'avisTill',
        'weekend_or_holiday_indicator' => 'weekendOrHolidayIndicator'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date' => 'setDate',
        'time_from' => 'setTimeFrom',
        'time_till' => 'setTimeTill',
        'avis_from' => 'setAvisFrom',
        'avis_till' => 'setAvisTill',
        'weekend_or_holiday_indicator' => 'setWeekendOrHolidayIndicator'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date' => 'getDate',
        'time_from' => 'getTimeFrom',
        'time_till' => 'getTimeTill',
        'avis_from' => 'getAvisFrom',
        'avis_till' => 'getAvisTill',
        'weekend_or_holiday_indicator' => 'getWeekendOrHolidayIndicator'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const WEEKEND_OR_HOLIDAY_INDICATOR_EMPTY = '';
    public const WEEKEND_OR_HOLIDAY_INDICATOR_S = 'S';
    public const WEEKEND_OR_HOLIDAY_INDICATOR_H = 'H';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWeekendOrHolidayIndicatorAllowableValues()
    {
        return [
            self::WEEKEND_OR_HOLIDAY_INDICATOR_EMPTY,
            self::WEEKEND_OR_HOLIDAY_INDICATOR_S,
            self::WEEKEND_OR_HOLIDAY_INDICATOR_H,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('time_from', $data ?? [], null);
        $this->setIfExists('time_till', $data ?? [], null);
        $this->setIfExists('avis_from', $data ?? [], null);
        $this->setIfExists('avis_till', $data ?? [], null);
        $this->setIfExists('weekend_or_holiday_indicator', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getWeekendOrHolidayIndicatorAllowableValues();
        if (!is_null($this->container['weekend_or_holiday_indicator']) && !in_array($this->container['weekend_or_holiday_indicator'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'weekend_or_holiday_indicator', must be one of '%s'",
                $this->container['weekend_or_holiday_indicator'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date
     *
     * @return string|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string|null $date date
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets time_from
     *
     * @return string|null
     */
    public function getTimeFrom()
    {
        return $this->container['time_from'];
    }

    /**
     * Sets time_from
     *
     * @param string|null $time_from time_from
     *
     * @return self
     */
    public function setTimeFrom($time_from)
    {
        if (is_null($time_from)) {
            throw new \InvalidArgumentException('non-nullable time_from cannot be null');
        }
        $this->container['time_from'] = $time_from;

        return $this;
    }

    /**
     * Gets time_till
     *
     * @return string|null
     */
    public function getTimeTill()
    {
        return $this->container['time_till'];
    }

    /**
     * Sets time_till
     *
     * @param string|null $time_till time_till
     *
     * @return self
     */
    public function setTimeTill($time_till)
    {
        if (is_null($time_till)) {
            throw new \InvalidArgumentException('non-nullable time_till cannot be null');
        }
        $this->container['time_till'] = $time_till;

        return $this;
    }

    /**
     * Gets avis_from
     *
     * @return string|null
     */
    public function getAvisFrom()
    {
        return $this->container['avis_from'];
    }

    /**
     * Sets avis_from
     *
     * @param string|null $avis_from avis_from
     *
     * @return self
     */
    public function setAvisFrom($avis_from)
    {
        if (is_null($avis_from)) {
            throw new \InvalidArgumentException('non-nullable avis_from cannot be null');
        }
        $this->container['avis_from'] = $avis_from;

        return $this;
    }

    /**
     * Gets avis_till
     *
     * @return string|null
     */
    public function getAvisTill()
    {
        return $this->container['avis_till'];
    }

    /**
     * Sets avis_till
     *
     * @param string|null $avis_till avis_till
     *
     * @return self
     */
    public function setAvisTill($avis_till)
    {
        if (is_null($avis_till)) {
            throw new \InvalidArgumentException('non-nullable avis_till cannot be null');
        }
        $this->container['avis_till'] = $avis_till;

        return $this;
    }

    /**
     * Gets weekend_or_holiday_indicator
     *
     * @return string|null
     */
    public function getWeekendOrHolidayIndicator()
    {
        return $this->container['weekend_or_holiday_indicator'];
    }

    /**
     * Sets weekend_or_holiday_indicator
     *
     * @param string|null $weekend_or_holiday_indicator weekend_or_holiday_indicator
     *
     * @return self
     */
    public function setWeekendOrHolidayIndicator($weekend_or_holiday_indicator)
    {
        if (is_null($weekend_or_holiday_indicator)) {
            throw new \InvalidArgumentException('non-nullable weekend_or_holiday_indicator cannot be null');
        }
        $allowedValues = $this->getWeekendOrHolidayIndicatorAllowableValues();
        if (!in_array($weekend_or_holiday_indicator, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'weekend_or_holiday_indicator', must be one of '%s'",
                    $weekend_or_holiday_indicator,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['weekend_or_holiday_indicator'] = $weekend_or_holiday_indicator;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


