<?php
/**
 * OrderResponseTransitInfoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\goexpress
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GO! Connect Realtime Order & Label API
 *
 * API for creating, updating, canceling shipments and generating labels for GO! Express & Logistics.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kruegge82\goexpress\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderResponseTransitInfoTest Class Doc Comment
 *
 * @category    Class
 * @description OrderResponseTransitInfo
 * @package     kruegge82\goexpress
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderResponseTransitInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderResponseTransitInfo"
     */
    public function testOrderResponseTransitInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dates_verified"
     */
    public function testPropertyDatesVerified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "addresses_verified"
     */
    public function testPropertyAddressesVerified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
