<?php
/**
 * ShipmentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\goexpress
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GO! Connect Realtime Order & Label API
 *
 * API for creating, updating, canceling shipments and generating labels for GO! Express & Logistics.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kruegge82\goexpress\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentTest Class Doc Comment
 *
 * @category    Class
 * @description Core shipment object containing all parameters needed for order creation, update, or cancellation.
 * @package     kruegge82\goexpress
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Shipment"
     */
    public function testShipment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hwb_number"
     */
    public function testPropertyHwbNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "order_status"
     */
    public function testPropertyOrderStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "validation"
     */
    public function testPropertyValidation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_reference"
     */
    public function testPropertyCustomerReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "self_pickup"
     */
    public function testPropertySelfPickup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "self_delivery"
     */
    public function testPropertySelfDelivery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dimensions"
     */
    public function testPropertyDimensions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "package_count"
     */
    public function testPropertyPackageCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "freight_collect"
     */
    public function testPropertyFreightCollect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ident_check"
     */
    public function testPropertyIdentCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receipt_notice"
     */
    public function testPropertyReceiptNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_neutral_pickup"
     */
    public function testPropertyIsNeutralPickup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pickup"
     */
    public function testPropertyPickup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value_of_goods"
     */
    public function testPropertyValueOfGoods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_on_delivery"
     */
    public function testPropertyCashOnDelivery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
